chuffed_lib_files += files(
    'MDD.cpp'
  , 'mdd_prop.cpp'
  , 'mdd_to_lgraph.cpp'
  , 'opcache.cpp'
  , 'weighted_dfa.cpp'
  , 'wmdd_prop.cpp'
  )

install_headers(
    'CFG.h'
  , 'circ_fns.h'
  , 'circutil.h'
  , 'CYK.h'
  , 'MDD.h'
  , 'mdd_prop.h'
  , 'mdd_to_lgraph.h'
  , 'opcache.h'
  , 'opts.h'
  , 'sorters.h'
  , 'weighted_dfa.h'
  , 'wmdd_prop.h'
  , subdir: 'chuffed/mdd'
  )
