chuffed_lib_files += files(
    'alldiff.cpp'
  , 'bool_arg_max.cpp'
  , 'bounded_path.cpp'
  , 'circuit.cpp'
  , 'cumulative.cpp'
  , 'cumulativeCalendar.cpp'
  , 'dag.cpp'
  , 'dconnected.cpp'
  , 'directives.cpp'
  , 'disjunctive.cpp'
  , 'dtree.cpp'
  , 'EdExplFinder.cpp'
  , 'edit_distance.cpp'
  , 'graph.cpp'
  , 'lex.cpp'
  , 'linear-bool.cpp'
  , 'linear-bool-decomp.cpp'
  , 'mddglobals.cpp'
  , 'minimum.cpp'
  , 'minimum_weight_tree.cpp'
  , 'mst.cpp'
  , 'regular.cpp'
  , 'subcircuit.cpp'
  , 'sym-break.cpp'
  , 'table.cpp'
  , 'template.cpp'
  , 'tree.cpp'
  , 'value-precede.cpp'
  , 'well-founded.cpp'
  )

install_headers(
    'bounded_path.h'
  , 'dag.h'
  , 'dconnected.h'
  , 'dtree.h'
  , 'EdExplFinder.h'
  , 'globals.h'
  , 'graph.h'
  , 'mddglobals.h'
  , 'tree.h'
  , subdir: 'chuffed/globals'
  )
