chuffed_lib_files += files(
    'dijkstra.cpp'
  , 'kosaraju_scc.cpp'
  , 'lengauer_tarjan.cpp'
  , 'union_find.cpp'
  )

install_headers(
    'BVec.h'
  , 'dijkstra.h'
  , 'dynamic_kmeans.h'
  , 'floyd_warshall.h'
  , 'heap.h'
  , 'kosaraju_scc.h'
  , 'lengauer_tarjan.h'
  , 'misc.h'
  , 'ParseUtils.h'
  , 'set_finder.h'
  , 'sparse_set.h'
  , 'trailed_cst_list.h'
  , 'union_find.h'
  , 'vec.h'
  , subdir: 'chuffed/support'
  )
