chuffed_lib_files += files(
    'bool-view.cpp'
  , 'int-var.cpp'
  , 'int-var-el.cpp'
  , 'int-var-ll.cpp'
  , 'int-var-sl.cpp'
  , 'modelling.cpp'
  )

install_headers(
    'bool-view.h'
  , 'int-var.h'
  , 'int-var-el.h'
  , 'int-var-ll.h'
  , 'int-var-sl.h'
  , 'int-view.h'
  , 'modelling.h'
  , 'vars.h'
  , subdir: 'chuffed/vars'
  )
